# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot-prerelease" do
  version "1.9.7-prerelease+5176573e"

  on_macos do
    on_intel do
      sha256 "8a9c8d4968f05911a08cab561687a5eea44085ae2b4574801b9021b3c1ab6a9a"
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a82d7fd159e1bd3bf0ce6fb8d66d3f7d84425dbeaacc33540c756ee22fb24ef"
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f90a8cf443df809b40ac7997668731ed0dd510bb8ff8d48f2646b6296feab050"
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4a3fd929b6654b5a2c50b2357b61b19185ccded300dd53ac78bad19b38ee6029"
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_arm64.tar.gz"
    end
  end

  name "pilot-prerelease"
  desc "Pilot is a tool for managing a local development environment using kubernetes (prerelease)"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "pilot",
    ]

  binary "pilot"
  generate_completions_from_executable "pilot",
    shell_parameter_format: :cobra

  # No zap stanza required

end
