# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot" do
  version "1.7.1"

  on_macos do
    on_intel do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_x86_64.tar.gz"
      sha256 "d7cab2fc4369be53b4937b1b9fb734e3362589112fa4df7d0706226e7d3719ea"
    end
    on_arm do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_arm64.tar.gz"
      sha256 "bf55efbb9db0c2beb296f88abaa49c53f69907fb290c9d324cd305ff393fbd7f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_x86_64.tar.gz"
      sha256 "e081e60efae225c19fa621293bf9287bf71da2ea6d3002d6c3cca4a9b4a6ae0c"
    end
    on_arm do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_arm64.tar.gz"
      sha256 "6c2961645d7f64269bf980ddfed221d7d94b36612abdc0ab806af3092e9df2f1"
    end
  end

  name "pilot"
  desc "Pilot is a tool for managing a local development environment using kubernetes"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "pilot-prerelease",
    ]

  binary "pilot"
  generate_completions_from_executable "pilot",
    shell_parameter_format: :cobra

  # No zap stanza required

end
