# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot" do
  version "1.7.2"

  on_macos do
    on_intel do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_x86_64.tar.gz"
      sha256 "a68b9152416d16584d98a31102c6dee89794ef69dc17fbf40db5e148b780ab96"
    end
    on_arm do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_arm64.tar.gz"
      sha256 "753afd58a1f6b701c05f8065751e0e3c2d36973b391b3504b1d1e6b855d9d80c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_x86_64.tar.gz"
      sha256 "14c17417ae564b83f26e47f37ad11a7a5895123a59371ff19a87556cc5754fa2"
    end
    on_arm do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_arm64.tar.gz"
      sha256 "408db6cb0c0356c48be5867b67427ea944e7153920accce0013ed4ddbec819a1"
    end
  end

  name "pilot"
  desc "Pilot is a tool for managing a local development environment using kubernetes"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "pilot-prerelease",
    ]

  binary "pilot"
  generate_completions_from_executable "pilot",
    shell_parameter_format: :cobra

  # No zap stanza required

end
