# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot-prerelease" do
  version "1.7.2-prerelease+d48c9fe2"

  on_macos do
    on_intel do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_x86_64.tar.gz"
      sha256 "aa8d2bfe289bb8af1a6e1a8bf79b045ea96bd0aa11716a12beeab2585dca4d6a"
    end
    on_arm do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_arm64.tar.gz"
      sha256 "501521b260712fc12ed069fe527187ebde2e87ba3c987e8fe06d4e3c3a66732e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_x86_64.tar.gz"
      sha256 "b0092c5cbcd5f1e02eac7990c251c05e7b5cb4dbe495198d179c589f82a84eb3"
    end
    on_arm do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_arm64.tar.gz"
      sha256 "cec2bc5a90bbbc074f6461ef28c9559a52fc5e4d583bae8801249f1cbe7083a4"
    end
  end

  name "pilot-prerelease"
  desc "Pilot is a tool for managing a local development environment using kubernetes (prerelease)"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "pilot",
    ]

  binary "pilot"
  generate_completions_from_executable "pilot",
    shell_parameter_format: :cobra

  # No zap stanza required

end
