# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot" do
  version "1.8.15"

  on_macos do
    on_intel do
      sha256 "89d98e08135c9db406d0141540d2be2915d0c2dac9fae21e4a2b780f6703f2c3"
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c93a30fd98081a846551169904d864aaea563170cdbc6d9318faa8cd1516536d"
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "056065c86dfefc1cf8801856b66cc00c142278b02ec230537853a017e84a3388"
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "55dcbddd05a428fcf3958c4fe3ac9a3f968d601ac8fabec8505a5fd6c0a10630"
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_arm64.tar.gz"
    end
  end

  name "pilot"
  desc "Pilot is a tool for managing a local development environment using kubernetes"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "pilot-prerelease",
    ]

  binary "pilot"
  generate_completions_from_executable "pilot",
    shell_parameter_format: :cobra

  # No zap stanza required

end
