# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot-prerelease" do
  version "1.7.1-prerelease+94db2400"

  on_macos do
    on_intel do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_x86_64.tar.gz"
      sha256 "b6bd77905e8f683066d333175d0b74612f487b42fce6998322a716946fb074ea"
    end
    on_arm do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Darwin_arm64.tar.gz"
      sha256 "3bd4591c83bd3b1301beb5d250c84d10f1d7fdae1266e77a4c6bead23a20b332"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_x86_64.tar.gz"
      sha256 "6b78a3e5a4c176fa3dc239613159d318aeea0d770c756ac8ea091190ccc67c6f"
    end
    on_arm do
      url "https://github.com/henriq/pilot/releases/download/v#{version}/pilot_Linux_arm64.tar.gz"
      sha256 "6fe30c873668c8321cba2764c3e9f98eac3b779cec4e85953df8813c718ddd3d"
    end
  end

  name "pilot-prerelease"
  desc "Pilot is a tool for managing a local development environment using kubernetes (prerelease)"
  homepage "https://henriq.se/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "pilot",
    ]

  binary "pilot"
  generate_completions_from_executable "pilot",
    shell_parameter_format: :cobra

  # No zap stanza required

end
